README.md, dev_tools/addCIToModule.js, dev_tools/skeletons/CI_and_build.yml, dev_tools/skeletons/npmpublish.yml
TICKET: https://openimis.atlassian.net/browse/OE0-90
=> OE0-90: added command in fe to add github workflows files to the chosen module

README.md, dev_tools/installModuleLocallyAll.js
TICKET: https://openimis.atlassian.net/browse/OE0-88
=> OE0-88: added command to pull modules to local workspace

src/ModulesManager.js
Comes after https://github.com/openimis/openimis-fe-core_js/pull/58
=> Contributions: use ensureArray to build contributions

README.md
part of TICKET: https://openimis.atlassian.net/browse/OP-766
added instruction based on my experience with helping to set up Gambian English localization.
=> OP-766: added section about translation based on experience to help with set up it

package.json
TICKET: https://openimis.atlassian.net/browse/OP-785 
Related TICKET: https://openimis.atlassian.net/browse/OSD-179
=> OP-785: updated version of fe on package.json to display proper version on main page

README.md
TICKET: https://openimis.atlassian.net/browse/OP-787
=> OP-787: added README section about handling most common errrors

src/helpers/theme.js
[OTC-856](https://openimis.atlassian.net/browse/OTC-856)
Changes:
- _buttonContainer_ class added to the _theme.js_.
[OTC-856]: https://openimis.atlassian.net/browse/OTC-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OTC-856: Add buttonContainer styles to the theme.js

openimis.json
TICKET: https://openimis.atlassian.net/browse/CM-97
=> CM-97: Fixed openimis.json module names

README.md
Ticket: https://openimis.atlassian.net/browse/ONI-114
Changes:
- Added missing step in the translations instructions.
=> ONI-114: Added missing step in translations instructions.

openimis.json
[CM-147](https://openimis.atlassian.net/browse/CM-147)
[FE-TASKS_MANAGEMENT MODULE REPO](https://github.com/openimis/openimis-fe-tasks_management_js/)
Changes:
- Add fe-tasks-management module to the _openimis.json_ file.
[CM-147]: https://openimis.atlassian.net/browse/CM-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CM-147: add tasks-management module to the openimis json

openimis.json
https://openimis.atlassian.net/browse/CM-214
Add grievance module to openimis.json. It also provides translation module to change names required by coreMIS.
it needs:
https://github.com/openimis/openimis-fe-coremis-language_en_js/pull/1
https://github.com/openimis/openimis-fe-grievance_js/pull/1
=> CM-214: add Grievance and coreMIS translation module

openimis.json
https://openimis.atlassian.net/browse/CM-212
It needs first: https://github.com/openimis/openimis-fe-payment_cycle_js/pull/1
=> CM-212: add payment cycle module to openimis.json

openimis.json
[CM-191](https://openimis.atlassian.net/browse/CM-191)
Changes:
- Attach Payroll module to the openimis.json.
[CM-191]: https://openimis.atlassian.net/browse/CM-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CM-191: Add payroll module to the openimis json

src/helpers/theme.js
https://openimis.atlassian.net/browse/OP-1533
This PR adds css for secondary highlight in searcher.
=> OP-1533: add secondary highlight css

openimis.json
[OM-78](https://openimis.atlassian.net/browse/OM-78)
[WORKER VOUCHER FE MODULE](https://github.com/openimis/openimis-fe-worker_voucher_js)
Changes:
- Add 'openimis-fe-worker_voucher_js' to the openimis json.
[OM-78]: https://openimis.atlassian.net/browse/OM-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OM-78: add worker_voucher module to the openimis json

dev_tools/installModuleLocallyAll.js, openimis.json, src/ModulesManager.js
[OM-125](https://openimis.atlassian.net/browse/OM-125)
Changes:
- Add ro-MD language (https://github.com/openimis/openimis-fe-language_ro_js).
- Improve script and assembling process (it was already done on develop branch: [MERGED PR](https://github.com/openimis/openimis-fe_js/pull/115))
[OM-125]: https://openimis.atlassian.net/browse/OM-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OM-125: add ro language, fix installAll script

dev_tools/installModuleLocally.js, dev_tools/installModuleLocallyAll.js
Fix scripts for fetching all modules at once.
=> hotfix: fix scripts

src/translations/ref.json
[OP-1848](https://openimis.atlassian.net/browse/OP-1848)
https://github.com/openimis/openimis-fe-core_js/pull/212
Changes:
- Update ref translations.
[OP-1848]: https://openimis.atlassian.net/browse/OP-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1848: update ref translations

openimis.json
https://openimis.atlassian.net/browse/CM-855
It needs: https://github.com/openimis/openimis-fe-grievance_social_protection_js/pull/1
=> CM-855: add grievance_social_protection module

modules-config.js, openimis-config.js, openimis.json, src/translations/ref.json
Merge the most recent develop branch into the release one.
=> fix: merge develop branch to the release one
